### ISSUE TITLE
Allow passing a base URL in meatie.Client

### ISSUE THREAD

**Issue by DefiDebauchery** [pmateusz/meatie#68]
I have sort of a unique situation. My use of meatie is only one small part of my overall application, and I would like to re-use my ClientSession, which has already been set up with various default options (like enabling env for proxy data, custom `TCPConnector`, timeouts, etc).

There's no easy way (that I could find) to quickly and generally apply these options to another ClientSession, and I wouldn't want to apply the `base_url` to this CS instance because that would of course apply to unrelated tasks.

I recognize that this is more an aiohttp limitation (not supporting `base_url` in `.request()` that I could pass into `session_params=`) than meatie, but perhaps there's room to increase flexibility by allowing for a local base variable that is combined in `meatie.Client`?  This could also make `Client`s reusable for platforms that have a consistent API but available on different hostnames, utilizing the same ClientSession (thus potentially opening up strategies like `asyncio.gather()` across several instances at once).

**Comment by pmateusz** [comment]
Hi @DefiDebauchery,

If you use aiohttp library and want to use the same ClientSession for communication with different hosts, then I would not set `base_url`. This is an entirely optional convenience option.

Otherwise, if you would like to access some advanced options of aiohttp library I would consider implementing a custom client class following this example: https://github.com/pmateusz/meatie/blob/master/src/meatie_aiohttp/client.py). Meatie codebase contains analog implementations for httpx and requests. By doing it you will have full control over the way HTTP requests are being dispatched.

We had a similar challenge in my other project (i.e., large API is spread across 5 different hosts). We ended up implementing 5 meatie clients with independent Client Sessions. We considered it best tradeoff because each of these hosts behaved differently in terms of error handling and rate limit policies.

**Comment by DefiDebauchery** [comment]
fwiw, I just noticed another reason this would be helpful: aiohttp only allows domains as its base_url, whereas many APIs might have a path prefix (that would be redundant to add to every `@endpoint`)

This was actually pretty easy to implement in a subclassed Client; would you accept a (cleaned up) PR to implement this flexibility? Granted I can only speak to aiohttp as that's what I use.


```py
from meatie_aiohttp import Client as OrigClient

class Client(OrigClient):
    def __init__(
            self,
            session: aiohttp.ClientSession,
            session_params: Optional[dict[str, Any]] = None,
            local_cache: Optional[Cache] = None,
            limiter: Optional[Any] = None,
            base_url: Optional[str] = None
    ) -> None:
        if base_url:
            self.base_url = base_url

        super().__init__(session, session_params, local_cache, limiter)

    async def send(self, request: Request) -> AsyncResponse:
        if not self.session._base_url:
            if self.base_url:
                request.path = self.base_url + request.path

        return await super().send(request)
```

**Comment by pmateusz** [comment]
@DefiDebauchery, I wasn't aware that `aiohttp` allows only subdomains as base_url.

Sure, I will accept the PR that adds `base_url: Optional[str] = None` as an argument to the constructor ([class Client(BaseAsyncClient)](https://github.com/pmateusz/meatie/blob/master/src/meatie_aiohttp/client.py#L23). Thank you for your useful suggestions and efforts to improve the library :bow:

**Comment by DefiDebauchery** [comment]
Hi @pmateusz, I got a chance to update to 0.1.14 and the `prefix` works wonderfully. Thanks so much!

As an aside, I've been mentioning meatie on Twitter and through Discord; hope this will help add some well-deserved attention!
